In [1]:
!pip install langchain_community

Requirement already satisfied: langchain_community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (1.2.19)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.7.16)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.41.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.1.0)

In [2]:
!pip install langchain_huggingface

Collecting langchain_huggingface
  Downloading langchain_huggingface-1.2.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.6.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.11 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.2.19)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (0.22.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (0.7.16)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (0.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.11->langchain_huggingface) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.1.2)
Downloading langchain_huggingface-1.2.1-py3-none-any.whl (30 kB)
Installing collected packages: langchain_huggingface
Successfully installed langchain_huggingface-1.2.1

In [3]:
!pip install langchain_chroma

Requirement already satisfied: langchain_chroma in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.5.5)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.2.19)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (2.0.2)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.41.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.26.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.7.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (26.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.14.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.0.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.10)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.3.0)

In [4]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [5]:
!pip install sentence-transformers chromadb

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.5)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.41.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

In [8]:
import pandas as pd

books = pd.read_csv("/content/books_cleaned.csv")

In [9]:
books["tagged_description"].to_csv(
    "tagged_description.txt",
    sep="\n",
    index=False,
    header=False
)

In [10]:
raw_documents = TextLoader("tagged_description.txt").load()

In [16]:
text_splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=1000,
    chunk_overlap=0
)

In [17]:
documents = text_splitter.split_documents(raw_documents)
documents[0]

WARNING:langchain_text_splitters.base:Created a chunk of size 1168, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1214, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1189, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1267, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2010, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1225, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1184, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1214, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1191, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1057, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1270, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1635, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1132, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1325, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1119, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1195, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2012, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1286, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1231, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1242, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1126, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1073, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1318, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2834, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1141, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1004, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2510, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1422, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1083, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1144, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1086, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1812, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1830, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1180, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1284, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1642, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1930, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2008, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2285, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1003, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1142, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1143, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1086, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1483, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1135, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1032, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1015, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1912, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2616, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1580, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1530, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2030, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1619, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1189, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1282, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1277, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1056, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1163, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1058, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1084, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2762, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1033, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1010, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1224, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1805, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1771, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1270, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1019, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1177, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1715, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1681, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1128, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2005, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1171, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2141, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1322, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1112, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1316, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1121, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1018, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1007, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1057, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1255, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1098, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1143, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1550, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1652, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1495, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1277, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1046, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1666, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1616, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1095, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1597, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1960, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1708, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1947, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1027, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1807, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1518, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1087, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1093, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1167, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1259, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1480, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1037, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1085, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1443, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1266, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1144, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1369, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1622, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1165, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1176, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1179, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1009, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1022, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1357, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1172, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1394, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1216, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2209, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1371, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2877, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1279, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1714, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1638, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2398, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2120, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1488, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1691, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1418, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1173, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1359, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2181, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1093, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2171, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1454, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1454, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1973, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1987, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1648, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2723, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1632, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1284, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1484, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1049, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1003, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1150, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1216, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1032, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2456, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1349, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1271, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1117, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1548, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1201, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1160, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1149, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1024, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1774, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1165, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1009, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1323, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1213, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1123, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1598, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1963, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 2450, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1796, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1568, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1219, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1380, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1452, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1102, which is longer than the specified 1000
WARNING:langchain_text_splitters.base:Created a chunk of size 1298, which is longer than the specified 1000

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [22]:
persist_dir = "chroma_books_db"
import os
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

if not os.path.exists(persist_dir):
    print("⏳ Creating embeddings... (this happens only once)")

    db_books = Chroma.from_documents(
        documents=documents,
        embedding=embedding_model,
        persist_directory=persist_dir
    )

    print("Database created and saved!")

else:
    print("Loading existing database (fast)")

    db_books = Chroma(
        persist_directory=persist_dir,
        embedding_function=embedding_model
    )

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading existing database (fast)

In [25]:
len(documents)

2932

In [26]:
db_books._collection.count()

0

In [27]:
import shutil
import os

if os.path.exists("chroma_books_db"):
    shutil.rmtree("chroma_books_db")

In [31]:
import shutil
import os

persist_dir = "chroma_books_db"
new_persist_dir = "chroma_books_db_new" # Use a new directory name to avoid lingering locks

# Ensure a clean slate before creating a new database
# Remove both old and potentially new directories for a clean run
if os.path.exists(persist_dir):
    shutil.rmtree(persist_dir)
    print(f"Removed existing {persist_dir} directory.")
if os.path.exists(new_persist_dir):
    shutil.rmtree(new_persist_dir)
    print(f"Removed existing {new_persist_dir} directory.")

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(
    documents=documents,
    embedding=embedding_model,
    persist_directory=new_persist_dir # Use the new directory
)
print(f"Chroma database created at {new_persist_dir}.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Chroma database created at chroma_books_db_new.

In [32]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='e4699c67-cb75-47b6-8986-fa5e5f776c90', metadata={'source': 'tagged_description.txt'}, page_content="9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.\n9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='5ee75838-854f-4288-8e58-b0a4eb6cd99f', metadata={'source': 'tagged_description.txt'}, page_content="9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author's father].' 'BL. 1986 Children's Editors' Choices (BL) Children's Choices for 1987 (IRA/CBC) Notable 1986 Childrens' Trade Books in Social Studies (NCSS/CBC) 1986 Children's Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"),
 Document(id='52923201-9e86-40a7-8ca8-6966960e90bf', metadata={'source': 'tagged_description.txt'}, page_content="9780142402931 A young girl from an advanced civilization is sent as an observer to a planet whose people have not yet learned to control their use of atomic power.\n9780142403013 After dreaming that they must leave their isolated home of Riverworld, Kyreol and Terje travel beyond what they believe to be end of the world, where they discover new planets and new ways of life. Reissue.\n9780142403204 Sixteen original stories showcase some of the genre's most admired authors, including multiple award-winners Diana Wynne Jones, Garth Nix, Lloyd Alexander, Nancy Farmer, and Meredith Ann Pierce. An ALA Best Book for Young Adults. Reprint.\n9780142404201 Each of five children lucky enough to discover an entry ticket into Mr. Willy Wonka's mysterious chocolate factory takes advantage of the situation in his own way."),
 Document(id='5807b329-5fb6-4c47-92ac-06783fd8c038', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects.\n9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='f6fa52b5-a59b-48c5-9730-1cbb32295b5e', metadata={'source': 'tagged_description.txt'}, page_content='"9781593851170 ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."'),
 Document(id='3a7535c2-e2f7-4813-ae0f-93aa3a6b943e', metadata={'source': 'tagged_description.txt'}, page_content="9780374517885 The Noble laureate has selected nearly 150 of his acclaimed stories, from his eight previous collections, offering abundant evidence of his mastery of the genre\n9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters.\n9780374522872 An account of a kayak and canoe journey through the Brooks Range wilderness, impressions of urban life and political activity, and portraits of people in the bush make up a study of contemporary Alaska"),
 Document(id='dfb1f437-83c7-4d19-aa1c-c3b3d07208e1', metadata={'source': 'tagged_description.txt'}, page_content="9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat's community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it's hard to evade questions forever. Children's Choices for 1991 (IRA/CBC)VOYA's Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"),
 Document(id='1606af33-b1ef-4eb5-9519-21f9144a3401', metadata={'source': 'tagged_description.txt'}, page_content="9780941807555 THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."),
 Document(id='58497844-8a94-4d30-8d13-74c5303be8d6', metadata={'source': 'tagged_description.txt'}, page_content="9780393930139 Long the standard teaching anthology, the landmark Norton Anthology of Literature by Women has introduced generations of readers to the rich variety of women's writing in English.\n9780393959055 The classic chronicle of a communion with nature at Walden Pond offers a message of living simply and in harmony with nature, and Thoreau champions the belief that people of conscience are at liberty to follow their own opinions."),
 Document(id='f197478f-e599-431a-8f69-478b66418798', metadata={'source': 'tagged_description.txt'}, page_content="9780064406925 The Little House books tell the story of a little pioneer girl and her family as they traveled by covered wagon across the Midwest. Laura Ingalls Wilder's classic books, illustrated with Garth Williams' timeless artwork, have been cherished by millions of readers ever since they were first published over sixty years ago. This My First Little House Book introduces Almanzo Wilder, the young boy from Farmer Boy who would one day marry Laura Ingalls. In Winter on the Farm, Almanzo goes through his afternoon barn chores, and then sits down to eat a hearty farm supper with his family. In this first book about Almanzo, young readers are able to share in the warmth and joy of another Little House family and celebrate new Little House adventures. Winter on the Farm is the first in an ongoing series about Laura’s beloved farmer boy.")]

In [33]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [38]:
def retrieve_semantic_recommendations(
    query: str,
    top_k: int = 5,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=top_k)

    books_list = []

    for rec in recs:
        isbn = int(rec.page_content.strip('"').split()[0])
        books_list.append(isbn)

    return books[books["isbn13"].isin(books_list)]

In [39]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
816,9780142402931,0142402931,The Far Side of Evil,Sylvia Engdahl,Juvenile Fiction,http://books.google.com/books/content?id=7nijj...,A young girl from an advanced civilization is ...,2005.0,3.98,324.0,57.0,The Far Side of Evil,9780142402931 A young girl from an advanced ci...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
4898,9781593851170,1593851170,The Nature of Play,Anthony D. Pellegrini;Peter K. Smith,Psychology,http://books.google.com/books/content?id=Nukz6...,"""Comprehensive and up to date, this tightly ed...",2005.0,4.25,308.0,4.0,The Nature of Play: Great Apes and Humans,"9781593851170 ""Comprehensive and up to date, t..."

I think we need improvement in recommendations. I will switch to zero shot classification to enhance the process.